name: "Kaia Chat UI - Publish"

on:
  push:
    branches: [main,feat/add-CICD]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0
          registry-url: https://registry.npmjs.org/

      - name: Build kaia-chat-ui js package
        shell: bash
        run: |
          npm install && npm run build

      - name: Publish kaia-chat-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public 

